language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_install:
  - chmod +x gradlew

before_deploy:
#  - zip -r springboot *
#  - mkdir -p deploy
#  - mv springboot.zip deploy/springboot.zip
  - mkdir -p before-deploy
  - cp script/*.sh before-deploy/
  - cp appspec.yml before-deploy/
  - cp build/libs/*.jar before-deploy/
  - cd ../ && mkdir -p deploy
  - mv before-deploy/before-deploy.zip deploy/springboot.zip


deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: springboot-bucket-golony
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: springboot-bucket-golony
    key: springboot.zip
    bundle_type: zip
    application: springboot-codedeploy
    deployment_group: springboot-deploy-group
    region: ap-northeast-2
    wait-until-deployed: true