language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

# CI 완료시 이메일 알림
#notifications:
#  email:
#    recipients:
#      - ab6449@gmail.com